#!/bin/bash

eval $(xrandr | grep '*' | \
    sed -e "s/^ \+\([0-9]\+\)x\([0-9]\+\).*/export WIDTH=\1 ; export HEIGHT=\2/p")
WIDTH_HALF=$((WIDTH/2))
HEIGHT_HALF=$((HEIGHT/2))

#wmctrl -r :ACTIVE: -b remove,maximized_horz,maximized_vert

case "$1" in
    max-toggle)
        wmctrl -r :ACTIVE: -b toggle,maximized_horz,maximized_vert
        ;;
    max-left)
        xdotool getactivewindow windowmove 0 y windowsize 50% y
        wmctrl -r :ACTIVE: -b add,maximized_vert
        ;;
    max-right)
        xdotool getactivewindow windowmove $WIDTH_HALF y windowsize 50% y
        wmctrl -r :ACTIVE: -b add,maximized_vert
        ;;
    *)
        echo $"Usage: $0 {max|min|max-left|max-right}"
        exit 1
esac