#!/bin/sh

bind-pacman && \
bind-torrent && \

# Resume all transmission torrents.
echo 'Starting transmission...' && \
    sudo systemctl start transmission && \
    echo 'Transmission started.' && \
transmission-remote -t all --start && \

# Allow trailing backslash on the last line of the command chain
true
