#!/bin/bash

# Device parameters.
LABEL=${LABEL:-Passport}
DFILE=/dev/disk/by-label/$LABEL
DMTPT=/media/$LABEL

# Directory parameters.
ARCH=`uname -m`
RDIR=$DMTPT/Arch\ Linux\ Packages/$ARCH

DIRS=(abs/community abs/core abs/extra abs/local/pkgs abs/local/srcpkgs \
      cache/pacman/pkg cache/pkgfile lib/pacman/sync)

case $1 in
    start)
        # Mount device (after unmounting any existing mount for this device)
        udevil info /dev/disk/by-label/$LABEL | grep 'is mounted' | grep '1' > /dev/null && udevil umount $DFILE
        udevil mount $DFILE || { echo "Mounting $LABEL device failed. Aborting..." 1>&2 ; exit ; }

        for DIR in "${DIRS[@]}"; do
            # Merge system files into mounted block device first.
            sudo mv -f "/var/${DIR}/*" "${RDIR}/var/${DIR}" &> /dev/null
            # Bind system path to mounted device.
            sudo mount --bind "${RDIR}/var/${DIR}" "/var/${DIR}"
        done
        ;;
    stop)
        for DIR in "${DIRS[@]}"; do
            # Unbind system path.
            sudo umount "/var/${DIR}" > /dev/null
        done

        # Unmount device
        udevil umount $DFILE
        ;;
    *)
        echo "usage: $0 (start|stop)"
        exit 1
esac
